const HomeActionType = {
  ADD: "ADD",
  MINUS: "MINUS",
  FETCH_USERS_START: "FETCH_USERS_START",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_ERROR: "FETCH_USERS_ERROR",
};

export default HomeActionType;
